### ISSUE TITLE
Add support for laravel 5.3

### ISSUE THREAD

**Issue by SamyOteroGlez** [SamyOteroGlez/larawesomecrud#19]

**Comment by rascoop** [comment]
Just did a pull request that closes this issue

**Comment by SamyOteroGlez** [comment]
Thanks rascoop, for spent time digging into this project. I really appreciated. 

I have an idea how add the support to the laravel versions. At this moment I'm using laravel 5.1, that's why I'm using route.php to add the new routes when the code its generated. Since the laravel 5.4 version have the routes in the file web.php, I was thinking in add a configuration file to declare all those elements that could change in laravel from one version to the next one, the models path, the routes path, the laravel version, the blacklist tables, etc, and also it will give more flexibility to the library, for example, if you want to store your models in a folder named MyModels, you just need to change the path to the models in that conf file. I was thinking in adding a new command, "--install" wish will create the configuration file for you, and you could pass the laravel version you are using to that command and also it will generates the configuration file according that version.

Regards.

Samy.

**Comment by rascoop** [comment]
Buenos Dias,
I think it's an excellent idea. So you will make both a command line parameter and the config file?

**Comment by SamyOteroGlez** [comment]
Hi, Buenos Dias,

Yes, that's the plan. If you check the milestone "Configuration file" you'll find there the user histories. I'm planning rewrite a lot, almost everything to have a more atomic and clean code, easy to extend and well documented. If interested I can share with you an image with the basic idea, the tech I'm using and you could pick some tasks.

At this moment I have the classes to handle the config file completed. I'm working on the database handler. But time is not enough, hahahaha.

Cheers.
